name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7f57cfc094424610e632618873e69a9f3fd57ff1a4213d73e863c86d216d51"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
