name = "Yet A Minecraft Mod Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e1ce6f03ac9e03bd6b10ccd67e570d69ec8f46d1b0af8aef017422bc3e2f200"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
