name = "Simple&Useful-Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "261e615c9a6902e65c109f59238f1b8d4534db977eadf7dd2a8a2982d14d668e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
