name = "C-Optimized"
author = "Cccc_"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6819ff52de04694a91acc0a4cc147bd5494f31fe217480ca34a9ff66502f1a85"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
