name = "Simple&Useful-Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182f1cafff4eb19059cafdcdc008d84a99498a8ccb1c31f3781ca4fc3aaae773"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
