name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de6f3b6b575c65708fe4ec89d824cadd8318a78c5bc34d2425cade9a0331e643"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
