name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcb31d50b0653e928b7225ede4f7a60eec60ece9db525fb42a27da65d20dd517"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
