name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bfc3a1be959f7577aa4ae0d013bbab79355b9f51c776753d0257a772d8f30e0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
