name = "MoreThanOptimize"
author = "Cccc_"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2765010b53159d16968a3856251b792bd3a65d71d44b40a265ab6f2cbe0058ea"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
