name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a271cceb1c7ef7cde5266b1d8ba8797b64fdb92b05d59c3fe3f21e52028719e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
