name = "MoreThanOptimize"
author = "Cccc_"
version = "3.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70b5609e0342394ec16ac07d3a860b214c905b0b609ffd3b0ffb89fd5ce01262"

[versions]
fabric = "0.16.8"
minecraft = "1.21.1"
