name = "MoreThanOptimize"
author = "Cccc_"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67669827cbce1d20ae7267aad2ac8fb0aced954a5805c4e41501ab141fa3f63c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
