name = "Yet A Minecraft Mod Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda0491d976ebd44548c046efb82071338aa9afdab7b37d1eba114ee26ea2ae0"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
