name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.6.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf3e0f732761f8f6bf87258e3d5caabe3f90785217d463160f48c6aaa4ae31c"

[versions]
fabric = "0.16.8"
minecraft = "1.21.1"
