name = "MoreThanOptimize"
author = "Cccc_"
version = "3.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfac02516c42f98ca81b30a8f673d8932c7888eb8a211bd0ce81fcb1e0018476"

[versions]
fabric = "0.16.8"
minecraft = "1.21.1"
