name = "MoreThanOptimize"
author = "Cccc_"
version = "3.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8374b7772bc6842713e42f7ade343672fa6508bdf5a45e4f6202cbc536c46cfa"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
