name = "C'SimpleModPack"
author = "Cccc_"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3de5fdb562a8c91a483691778111df1167fa02e729803d770e5ae8d08c39e895"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
