name = "C'SimpleModPack"
author = "Cccc_"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df2e0f16942b7770d24d398d92bed60912427536e748c9fbeb12695f8f899015"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
