name = "Yet A Minecraft Mod Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbd2827042b4a5875576ae7fadf58ad558abc6caaef8186b948bee0b07533213"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
