name = "MoreThanOptimize"
author = "Cccc_"
version = "3.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4505f7f173c6814928d65658e264b049c23e80509118e1faa0e4a0992e8bb83"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
