name = "Yet A Minecraft Mod Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82107b9ffba576b8d919123429b55d5ac8a1fa55c074b5fb14229fec34d0ac9e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
