name = "MoreThanOptimize"
author = "Cccc_"
version = "3.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48f094eda4dd399adda31b09f0a5a44423bda17e94ed09ff10ebc33999a2925b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
