name = "MoreThanOptimize"
author = "Cccc_"
version = "3.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dadd68baf40d2b5186d050f3c93704175d4e7fdcb33459b625397147d7b1375a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
