name = "C'SimpleModPack"
author = "Cccc_"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e623c86bc18186a415a4131dcbda59fd07541074abd2e14e2bbe3407586ebbcc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
