name = "Simple&Useful-Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e889876bc241e19ff3c9b4ad1042f3d2f66e645b1f2d8e5d99f79b9d0300a9d1"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
