name = "Yet A Minecraft Mod Pack"
author = "Cccc_"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be25d2bc7d1955fd979f83646ab10b54fc750b2bc1a2a83420f8da9cb84bba5f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
