name = "MoreThanOptimize"
author = "Cccc_"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c22d1cb28aa6d1d029b9726dd91560add5e9c993a1d20723df327a322beffafb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
