name = "MoreThanOptimize"
author = "Cccc_"
version = "v3.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4286f43daba0c6d7ea5a180304b7b3c7269cc44d8d81913c7d16a83b94d84b9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
