name = "C'SimpleModPack"
author = "Cccc_"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1d89811cc3bb0f40711acaacd0d5f82dc5d9ad4aafce6dca40d029e2d161676"

[versions]
fabric = "0.15.10"
minecraft = "1.20.6"
