name = "MoreThanOptimize"
author = "Cccc_"
version = "3.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8d26a54b40fe03b980f1bdcdec933adfe67a6fd6fe1ef3e5226e60a4ff4273"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
